### ISSUE TITLE
运行未成功

### ISSUE THREAD

**Issue by sNpky** [raoyongming/CAL#11]
is:open 你好！代码拉取下来之后阅读readme 把数据集放在相应位置之后 就可以运行吗？我尝试这样，并未成功

**Comment by raoyongming** [comment]
感谢对我们工作的关注。环境配置正确应该能正常运行。能提供更具体的错误信息吗？

**Comment by sNpky** [comment]
我刚刚入门，我想问一下 项目是在linux下运行的吗？ 我是在windows跑的

**Comment by sNpky** [comment]
目前我正在学习 在ubuntu下搭建环境

**Comment by raoyongming** [comment]
我们的代码都是在linux上运行的

**Comment by sNpky** [comment]
好的好的，多谢提示

**Comment by sNpky** [comment]
![image](https://user-images.githubusercontent.com/54803073/161664327-7772f5e1-0e50-4a08-8e03-a0704e57324d.png)
我在ubuntu上搭建完环境，按照readme设置数据集，训练模型，但是到了评估的时候还是报错，和在windows报一样的错误。from models import WSDAN_CAL没有找到WSDAN_CAL

**Comment by sNpky** [comment]
我看了 models 里面的init ，调用几个文件中的函数，但是我在直接运行 infer.py就会报错找不到，是我的操作顺序有错误吗

**Comment by raoyongming** [comment]
从你提供的错误信息，可以试试把在fgvc文件夹而不是整个repo文件夹下运行infer.py。如果使用PyCharm可以试试只用fgvc文件夹建立项目。

**Comment by sNpky** [comment]
module 'torch.cuda' has no attribute 'amp'
![2022-04-05 18-16-47 的屏幕截图](https://user-images.githubusercontent.com/54803073/161732648-16edccc3-5136-417d-bb71-20445a10a1d2.png)
 本来models里面没有vgg.py 我根据readme提供的github地址 的pytorch项目 找到的gg

**Comment by sNpky** [comment]
现在这个报错我查到的解决方案 说是 torch.cuda.amp 属性是 在 torch1.6版本之后才有,但是项目readme 说是pytorch 1.0

**Comment by raoyongming** [comment]
好的，感谢反馈，我已经更新了代码。

**Comment by sNpky** [comment]
还有models里面用的到VGG 文件没有放过去，需要去readme里面的提供的git地址下载 放到这个fgvc的models里面

![image](https://user-images.githubusercontent.com/54803073/161741775-e0e21250-f27b-4d5b-a7f8-686bb22da607.png)

**Comment by raoyongming** [comment]
vgg这个文件是不需要的，我已经从cal把它删掉了

**Comment by sNpky** [comment]
但是 
![image](https://user-images.githubusercontent.com/54803073/161753021-803bfd24-4002-44b0-95f1-980bd79a859d.png)
![image](https://user-images.githubusercontent.com/54803073/161753039-ba32a4b2-d37a-46b7-9d37-f2015e6ee86c.png)
z这里还是在引用，我没用引入的时候还会报错

**Comment by raoyongming** [comment]
我更新了github的repo，你可以同步一下或者手动改一下。

**Comment by sNpky** [comment]
好的，我自己再试试，我的机器是只有一块GPU ，torch版本，cuda版本都正确，但是会报错invalid device ordinal，我还在尝试解决方案

**Comment by sNpky** [comment]
我想问一下 你们实验使用的 一台主机多块GPU吗 。 显卡型号都>1080ti吗？

**Comment by raoyongming** [comment]
我们的主要实验是在4x1080Ti上跑的

**Comment by sNpky** [comment]
好的好的，我尝试调整一下 项目中GPU的设置

**Comment by sNpky** [comment]
我修改了一些关于GPU的配置fgvc已经跑通，我不太清楚的就是，实验代码的数据集路径存在问题，需要自己手动添加一个如下图
![image](https://user-images.githubusercontent.com/54803073/162390254-a0fe3398-52b1-4082-8a53-083c0feec02a.png)
![image](https://user-images.githubusercontent.com/54803073/162390700-19db1299-30d9-49bd-b8e7-415aa4d3cc06.png)

**Comment by sNpky** [comment]
非常感谢 对我答疑提供的信息！我结合代码将仔细拜读你们的论文！

**Comment by raoyongming** [comment]
在我们的环境下，`CUB_200_2011`这个路径和`infer.py`在同一个层级。

**Comment by scutfrank** [comment]
> 好的，我自己再试试，我的机器是只有一块GPU ，torch版本，cuda版本都正确，但是会报错invalid device ordinal，我还在尝试解决方案

你好，我也是单GPU，想问下应该如何修改，谢谢

**Comment by lixiaoqianqian** [comment]
> > 好的，我自己再试试，我的机器是只有一块GPU ，torch版本，cuda版本都正确，但是会报错invalid device ordinal，我还在尝试解决方案
> 
> 你好，我也是单GPU，想问下应该如何修改，谢谢

您好，同问，单GPU，应该如何修改
