### ISSUE TITLE
Batch Size 和 准确率

### ISSUE THREAD

**Issue by Eorsion** [raoyongming/CAL#12]
作者你好，我阅读了您的文章，很受启发，并在GPU上复现了一下您的代码，发现代码中的batch_size=4，而论文里的batch_size=16，细粒度数据集CUB-200-2011跑出来的准确率为90%，然后我在batch_size=4的情况下，做了改进，在CUB-200-2011准确率为90.33%，请问下这样算创新了嘛

**Comment by raoyongming** [comment]
你好，感谢对我们工作的关注。我们采用的是DDP训练，使用4个GPU，每一个上面batch size是4，所以总体batch size是16。我之前没有试过更小的batch size，减小可能会对性能有影响。如果在同等条件下，你的改进提高了性能，那应该说明你的改进是有效的。

**Comment by Eorsion** [comment]
感谢作者的回复，我现在遇到的问题是，因为跑不到论文中的准确率，虽然加了创新点有提升，但是准确率仍没有达到90.6%，我不知道这样算不算创新




安辰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "raoyongming/CAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 下午3:02
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [raoyongming/CAL] Batch Size 和 准确率 (Issue #12)





 
你好，感谢对我们工作的关注。我们采用的是DDP训练，使用4个GPU，每一个上面batch size是4，所以总体batch size是16。我之前没有试过更小的batch size，减小可能会对性能有影响。如果在同等条件下，你的改进提高了性能，那应该说明你的改进是有效的。

**Comment by Eorsion** [comment]
谢谢作者的回复，我现在遇到一个问题，就是代码跑不到论文中的准确率，虽然加了创新点后确实提升了，但是仍没有达到90.6%，我不知道这样算不算创新。

**Comment by Eorsion** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
