### ISSUE TITLE
为什么没用和WS-DAN使用相同的主干网络？

### ISSUE THREAD

**Issue by Stephen-Hao** [raoyongming/CAL#2]
WS-DAN 使用的主干网络是inceptionV3，而CAL使用的是resnet101,后者性能明显比前者好，为什么论文中在不同数据集上对比时，没用也使用inceptionV3呢

**Comment by raoyongming** [comment]
Thanks for your interest in our paper.

We use the Pytorch implementation of WS-DAN from [this repo](https://github.com/GuYuc/WS-DAN.PyTorch). The performance is slower than the original paper (88.28 vs.  89.4).  To better compare with SOTA methods like API-NET, we use a stronger backbone. 

In our early experiments, we also found CAL can also improve WS-DAN based on Inception V3 (88.28 -> 89.32 on CUB).

**Comment by Stephen-Hao** [comment]
@raoyongming 好的，可能是我没用仔细看论文，感谢您的解答。
