### ISSUE TITLE
About WSDAN-CAL in the train_distributed.py

### ISSUE THREAD

**Issue by kanzmh** [raoyongming/CAL#21]
I've tried to train this code, but I'm still confused about understanding the code in the train_distributed.py file

![1](https://github.com/raoyongming/CAL/assets/75152777/a5c072ed-49c6-482d-bb3d-66791667227b)
In this coding, the aug variable uses the crop method, and the aux variable uses the drop method

![2](https://github.com/raoyongming/CAL/assets/75152777/73c3b8e2-549f-405c-b5c9-67536ac8ab91)
But why does the aug_images variable use both methods (crop&drop), not just the crop method?

Thank you

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. It should be a typo. As the printed message [here](https://github.com/raoyongming/CAL/blob/0ba9d5084f2532eeb21c9ef051c23f8b339595ff/fgvc/train_distributed.py#L254), `epoch_crop_acc` is the accuracy for images with extra data augmentations including both "crop" and "drop", and `epoch_drop_acc` is the accuracy for auxiliary predictions. It seems we use the wrong names for these two variables.

**Comment by kanzmh** [comment]
Can I ask again about the architecture of WSDAN_CAL and the visualization? Cause I'm still quite confused when I read the journal and the model results, thank you for your help.
