### ISSUE TITLE
about feature matrix which is the input of the last fc layer

### ISSUE THREAD

**Issue by lynlindasy** [raoyongming/CAL#4]
Sorry to bother you, I have a question about the fgvc part. Why the normalized feature_matrix and feature_matrix_hat need to multiply 100 before the fc layer?

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. We use the trick following the implementation of [WS-DAN](https://github.com/GuYuc/WS-DAN.PyTorch/blob/87779124f619ceeb445ddfb0246c8a22ff324db4/models/wsdan.py#L111). This trick is useful to improve the final performance while introducing no significant extra computations. There are some discussions (https://github.com/GuYuc/WS-DAN.PyTorch/issues/1) on this detail in the WS-GAN repo.

**Comment by lynlindasy** [comment]
> Interesting question! Since we are considering the attention-based models here, "no attention" actually can also be regarded as a type of counterfactual attention. It is the "uniform attention" compared in Table 4. We see the uniform counterfactual attention can also achieve comparable performance with the "random attention" used in most of our experiments.

Thank you a lot! I just started my work on fine-grained classification and I think your work is very interesting. Maybe I will try this method on my dataset later. Thank you again!
